### ISSUE TITLE
Strange, but context does not have method draw() 

### ISSUE THREAD

**Issue by linuxenko** [sidorares/ntk#23]
How do you make the [example](https://github.com/sidorares/ntk/blob/master/examples/text-rendering.js#L42) work , it fail on the `ctx1.draw` ? 
Maybe something wrong with my installation , i did `npm install ntk` and it just installed wtihout any issues, does it require something else to be installed or so ?

**Comment by linuxenko** [comment]
ah . it seems like something wrong with example itself, another one (from readme) work just fine. btw installed via `npm` example is slightly different, maybe it is a problem, idk, but context work and it is cool.

**Comment by sidorares** [comment]
yeah, some examples might be outdated, sorry. Any contributions are very welcomed :)
